AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "vendor/**/*"

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Naming/FileName:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 150